# Generated by Django 4.2.7 on 2023-11-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="visibility",
            field=models.CharField(
                choices=[("Public", "Công khai"), ("Private", "Riêng tư")],
                default="Public",
                max_length=20,
            ),
        ),
    ]
