# Generated by Django 4.2.7 on 2023-11-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="group_chat",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="name",
            field=models.CharField(default="test", max_length=1000),
            preserve_default=False,
        ),
    ]
