# Generated by Django 4.2.7 on 2023-11-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chatroom_group_chat_chatroom_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="avatar_room",
            field=models.ImageField(
                default="avatar-chatroom.jpg", upload_to="avatars/"
            ),
        ),
    ]
