# Generated by Django 4.2.7 on 2023-11-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_chatroom_avatar_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="slug",
            field=models.SlugField(default=123),
            preserve_default=False,
        ),
    ]
