# Generated by Django 4.2.7 on 2023-11-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_chatroom_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="slug",
            field=models.SlugField(default="123123"),
        ),
    ]
