# Generated by Django 4.2.7 on 2023-11-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_alter_chatroom_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="is_block",
            field=models.BooleanField(default=False),
        ),
    ]
