# Generated by Django 4.2.7 on 2023-11-23 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_blockchat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="is_block",
        ),
    ]
