# Generated by Django 4.2.7 on 2023-11-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_remove_chatroom_is_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="avatar_room",
            field=models.ImageField(default="avatar_default.jpg", upload_to="avatars/"),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="slug",
            field=models.SlugField(default="123123", unique=True),
        ),
    ]
