# Generated by Django 3.2.7 on 2023-11-08 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Công khai'), ('Friend', 'Bạn bè')], default='Public', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, upload_to='post', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'mp4', 'mov'])]),
        ),
    ]
