# Generated by Django 4.1 on 2023-11-15 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20231108_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, upload_to='post', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'mp4', 'mov', 'png'])]),
        ),
    ]
