"""
Django settings for SocialMedia project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_wa7p*$qra1!5^j0%e#6#i4b)o5=9in98%4fq+@15q*e92!c%k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = '21211tt3528@mail.tdc.edu.vn'  # Thay thế bằng email của bạn
EMAIL_HOST_PASSWORD = 'bvce evdq xyoo jmvg'  # Thay thế bằng mật khẩu của bạn
ALLOWED_HOSTS = []

ASGI_APPLICATION = 'SocialMedia.asgi.application'
# Application definition

# CHAT
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}


INSTALLED_APPS = [
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # app chat
    'daphne',
    # add django channels
    'channels' , 

    'django.contrib.staticfiles',
    
    'posts',
    'profiles',
    'notification',
    'sendemail',
    'chat',
    'group',


    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'profiles.middleware.LoginRequiredMiddleware',
    'posts.middleware.LoginRequiredMiddleware',

]

ROOT_URLCONF = 'SocialMedia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SocialMedia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Đoạn code này định nghĩa tiền tố URL cho các tệp tĩnh. Tệp tĩnh là các tệp không được tạo động, 
# chẳng hạn như CSS, JavaScript và hình ảnh. Giá trị 'static/' có nghĩa là tất cả các tệp tĩnh sẽ được phục vụ từ thư mục /static/.
STATIC_URL = 'static/'

# Đoạn code này định nghĩa một danh sách các thư mục nơi Django nên tìm kiếm các tệp tĩnh. 
# Giá trị [os.path.join(BASE_DIR, 'static_project')] có nghĩa là Django sẽ tìm kiếm các tệp tĩnh trong thư mục static_project trong thư mục gốc của dự án.
STATICFILES_DIRS =[
    os.path.join(BASE_DIR, 'static_project')
]
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR),"static_cdn", "static_root")
# Đoạn code này định nghĩa tiền tố URL cho các tệp media. Tệp media là các tệp được tạo động, 
# chẳng hạn như ảnh và video được người dùng tải lên. Giá trị '/media/' có nghĩa là tất cả các tệp media sẽ được phục vụ từ thư mục /media/.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR),"static_cdn", "media_root")
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Sau khi login tự động qua trang theo đường link. Vd: http://127.0.0.1:8000/profiles/myprofile/
# LOGIN_REDIRECT_URL = '/profiles/myprofile/'
LOGIN_REDIRECT_URL = '/'
# Lâm
LOGOUT_REDIRECT_URL = '/login'
