# Generated by Django 4.1 on 2023-11-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='boygameso1lt@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
